In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score,
    brier_score_loss,
)
from sklearn.calibration import calibration_curve

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import RandomOverSampler

import optuna
import mlflow
import shap
from fairlearn.metrics import MetricFrame, demographic_parity_difference, equalized_odds_difference
import joblib

c:\Users\elima\Desktop\Supervised Learning Project - Group Muhammad-Jules-Elimane\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Need to display all data
pd.set_option("display.max_columns", None)
# pd.set_option("display.max_rows", None)

# Importing the data

In [3]:
from sklearn.datasets import fetch_openml
# Option 3 -- Diabetes 130 Hospitals
diabetes = fetch_openml(data_id=4541, as_frame=True)
X, y = diabetes.data, diabetes.target

In [4]:
df_diabetes= pd.DataFrame(diabetes.data)
df_diabetes

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide.metformin,glipizide.metformin,glimepiride.pioglitazone,metformin.rosiglitazone,metformin.pioglitazone,change,diabetesMed
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,MC,?,51,0,16,0,0,0,250.13,291,458,9,None,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,MC,?,33,3,18,0,0,1,560,276,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,MC,?,53,0,9,1,0,0,38,590,296,13,None,None,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,MC,Surgery-General,45,2,21,0,0,1,996,285,998,9,None,None,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,?,?,13,3,3,0,0,0,530,530,787,9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No

In [17]:
df_diabetes.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  category
 3   gender                    101766 non-null  category
 4   age                       101766 non-null  category
 5   weight                    101766 non-null  category
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  category
 11  medical_specialty         101766 non-null  category
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  category
 19  diag_2                    101766 non-null  category
 20  diag_3                    101766 non-null  category
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             101766 non-null  category
 23  A1Cresult                 101766 non-null  category
 24  metformin                 101766 non-null  category
 25  repaglinide               101766 non-null  category
 26  nateglinide               101766 non-null  category
 27  chlorpropamide            101766 non-null  category
 28  glimepiride               101766 non-null  category
 29  acetohexamide             101766 non-null  category
 30  glipizide                 101766 non-null  category
 31  glyburide                 101766 non-null  category
 32  tolbutamide               101766 non-null  category
 33  pioglitazone              101766 non-null  category
 34  rosiglitazone             101766 non-null  category
 35  acarbose                  101766 non-null  category
 36  miglitol                  101766 non-null  category
 37  troglitazone              101766 non-null  category
 38  tolazamide                101766 non-null  category
 39  examide                   101766 non-null  category
 40  citoglipton               101766 non-null  category
 41  insulin                   101766 non-null  category
 42  glyburide.metformin       101766 non-null  category
 43  glipizide.metformin       101766 non-null  category
 44  glimepiride.pioglitazone  101766 non-null  category
 45  metformin.rosiglitazone   101766 non-null  category
 46  metformin.pioglitazone    101766 non-null  category
 47  change                    101766 non-null  category
 48  diabetesMed               101766 non-null  category
dtypes: category(36), int64(13)
memory usage: 14.0 MB

# Target Analysis

In [11]:
target = y.value_counts()
target

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

We can see that for the target, it will be the "probability" of someone coming back to the hospital whether or not, whether before or after 30 days.
The original target has three categories (NO, >30, and <30); we will convert it into a binary outcome that identifies patients readmitted within 30 days of discharge.

The business goal is to help hospital discharge teams identify patients at higher risk and prioritize them for additional follow-up when resources are limited.
That way they will be able to organize the places according to the tension they have on it.

In [9]:
target = pd.DataFrame(y)
target

       readmitted
0              NO
1             >30
2              NO
3              NO
4              NO
...           ...
101761        >30
101762         NO
101763         NO
101764         NO
101765         NO

[101766 rows x 1 columns]